global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Reemplaza esto por el nombre y puerto real de tu servicio (ej. la app Flask
  # de tu pipeline de Jenkins que quieres monitorear)
  - job_name: "flask_service"
    static_configs:
      - targets: ["host.docker.internal:5000"]
